### ISSUE TITLE
First Sprint To-Do Items

### ISSUE THREAD

**Issue by jcconnell** [jcconnell/downl-od#1]
## First sprint objectives:
* gather all local files as a dict
* persists it
* parse an OD and ignore files indexed
* generate a wget script from that

Items discussed in the Gitter as good candidates to be addressed first.

**Comment by Krazybug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/wTZ39fAY/1-test)
